-- Users hold a balance and use an optimistic-locking version column.
CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance_eur NUMERIC(19, 2) NOT NULL,
    version     BIGINT         NOT NULL DEFAULT 0
);

-- Server-owned odds quotes issued when listing events. Single-use, expiring.
CREATE TABLE odds_quotes
(
    quote_id   UUID PRIMARY KEY,
    event_id   BIGINT      NOT NULL,
    driver_id  INTEGER     NOT NULL,
    odds       INTEGER     NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_odds_quotes_event ON odds_quotes (event_id);

-- Event outcomes. The PRIMARY KEY on event_id is the settlement idempotency guard.
CREATE TABLE event_outcomes
(
    event_id          BIGINT PRIMARY KEY,
    winning_driver_id INTEGER     NOT NULL,
    settled_at        TIMESTAMPTZ NOT NULL
);

-- Bets. The UNIQUE constraint on quote_id enforces atomic single-use of a quote.
CREATE TABLE bets
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT         NOT NULL REFERENCES users (id),
    event_id          BIGINT         NOT NULL,
    driver_id         INTEGER        NOT NULL,
    amount_eur        NUMERIC(19, 2) NOT NULL,
    odds_at_placement INTEGER        NOT NULL,
    status            VARCHAR(16)    NOT NULL,
    quote_id          UUID           NOT NULL UNIQUE REFERENCES odds_quotes (quote_id),
    placed_at         TIMESTAMPTZ    NOT NULL
);
CREATE INDEX idx_bets_event_status ON bets (event_id, status);
CREATE INDEX idx_bets_user ON bets (user_id);

